### ISSUE TITLE
Deprecated constants

### ISSUE THREAD

**Issue by lines27** [marq24/ha-senec-v3#81] opened 2024-02-12 12:50 UTC
Hello senec-team,
got the warnings, that the following contants are deprected and will be removed in HA Core 2025.1:

ENERGY_KILO_WATT_HOUR
POWER_WATT 
POWER_KILO_WATT 
TEMP_CELSIUS

**Comment by marq24** [comment] 2024-02-12 13:17
duplicate of #68

**Closed by marq24** 2024-02-12 13:17 UTC
